settings:
  port: 8000

alarms:
  -
    name: "Test"
    hour: 7
    minute: 0
    days:
      - 0
      - 1
    on: False
  -
    name: "Test2"
    hour: 9
    minute: 15
    days:
      - 0
      - 1
    on: False

radio:
  pid: -1
  running: False