name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build linux arm
      run: env GOOS=linux GOARCH=arm go build -o build/rpi_radio_alarm_arm -v .
    
    - name: Build linux 64
      run: env GOOS=linux GOARCH=amd64 go build -o build/rpi_radio_alarm_64 -v .

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: bins
        path: build/
